#!/usr/bin/env python3.6

import yaml
import json
import subprocess
import re
import pathlib
import os
from datetime import datetime
import argparse
import logging


def getargs():
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', required=False, action='store', help='config.yaml')
    parser.add_argument('--no-state', required=False, action='store_true',
        help='Not use state file and read whole logs')
    parser.add_argument('--state-dir', required=False, action='store',
        help='Dir to keep state files under (default: /tmp)', default='/tmp')

    args = parser.parse_args()
    return args


def load_yaml(directory_path, args_config):
    configfile = os.path.join(directory_path, 'config.yaml')
    if args_config:
        configfile = args_config

    yamlfile = open(configfile, 'r')

    return yaml.load(yamlfile)


def get_regex_pattern(yamlconf):
    pattern_list = list()
    if yamlconf is not None:
        pattern_list = yamlconf.get('stats')

    if pattern_list:
        pattern = re.compile('|'.join(pattern_list))
    else:
        pattern = re.compile('.')

    return pattern


def load_statsfile(statsfile):
    if not os.path.exists(statsfile):
        return None
    else:
        with open(statsfile, 'r') as f:
            stats = json.load(f)
            return stats


def save_statsfile(statsfile, data):
    with open(statsfile, 'w') as f:
        timestamp = int( datetime.now().timestamp() )
        f.write(
            json.dumps(data, indent=4)
        )


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)

    root = pathlib.Path(__file__)
    fullpath = root.resolve()
    directory_path = fullpath.parent

    args = getargs()
    statsfile = os.path.join(args.state_dir, fullpath.name)

    yamlconf = load_yaml(directory_path, args.config)
    pattern = get_regex_pattern(yamlconf)

    unbound_control = yamlconf.get('unbound_control', '/usr/sbin/unbound-control')
    metrics_key_prefix = yamlconf.get('metrics_key_prefix', 'unbound')
    metrics_key_suffix = yamlconf.get('metrics_key_suffix', None)
    metrics_key_remove = yamlconf.get('metrics_key_remove')

    timestamp = int( datetime.now().timestamp() )
    stats = subprocess.check_output([unbound_control, "stats"])

    data = {'timestamp': timestamp}
    for line in stats.decode("utf-8").split('\n'):
        if re.search(pattern, line):
            key, value = line.split('=')
            metrics_key = metrics_key_prefix + '.' + key

            if metrics_key_suffix is not None:
                metrics_key = metrics_key + '.' + metrics_key_suffix
            if metrics_key_remove:
                metrics_key = metrics_key.replace(metrics_key_remove, '')

            data[metrics_key] = value
            if args.no_state:
                print(metrics_key, value, timestamp, sep='\t')
    else:
        if args.no_state:
            exit()


    loaded = load_statsfile(statsfile)
    if loaded is None:
        logging.info('does not exist at last fetch')
    else:
        for key in data:
            if re.search(metrics_key_prefix, key):
                if not loaded.get(key):
                    continue
                value = int(data[key]) - int(loaded[key])
                print(key, value, timestamp, sep='\t')

    save_statsfile(statsfile, data)

